# Generated by Django 4.1.6 on 2023-02-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_number_lt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number_lt',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='number_lt',
            field=models.IntegerField(default=0),
        ),
    ]
