# Generated by Django 4.1.6 on 2023-02-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_number_lt_userprofile_number_lt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='user/profile_picture/default-avatar.jpeg', null=True, upload_to='user/profile_picture'),
        ),
    ]
