# Generated by Django 4.1.6 on 2023-02-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_alter_chapter_title_alter_story_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='number_of_chapter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='number_of_comment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='number_of_reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='number_of_views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='rating_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
