# Generated by Django 4.1.6 on 2023-02-11 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0012_listread'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='price',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='chapter',
            name='vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='story.story'),
        ),
    ]
