# Generated by Django 4.1.6 on 2023-02-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0013_chapter_price_chapter_vip_alter_comment_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='user_bought',
            field=models.BooleanField(default=False),
        ),
    ]
