# Generated by Django 4.1.6 on 2023-02-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0014_chapter_user_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='user_bought',
            field=models.CharField(max_length=50),
        ),
    ]
