# Generated by Django 4.1.6 on 2023-02-11 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0015_alter_chapter_user_bought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='user_bought',
        ),
    ]
