# Generated by Django 4.1.6 on 2023-02-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0016_remove_chapter_user_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='listread',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
