# Generated by Django 4.1.6 on 2023-02-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0017_listread_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='number_star_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
