# Generated by Django 4.1.6 on 2023-02-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0020_alter_story_number_of_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='number_like',
            field=models.IntegerField(default=0),
        ),
    ]
