# Generated by Django 4.1.6 on 2023-02-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0021_comment_number_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image_user',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
