# Generated by Django 4.1.6 on 2023-02-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0022_comment_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image_user',
            field=models.ImageField(upload_to=''),
        ),
    ]
