# Generated by Django 4.1.6 on 2023-02-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0023_alter_comment_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='number_reply',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
