# Generated by Django 4.1.6 on 2023-02-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0026_votestory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votestory',
            name='number_vote',
            field=models.IntegerField(default=0),
        ),
    ]
