# Generated by Django 4.1.6 on 2023-02-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0027_alter_votestory_number_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votestory',
            name='name_story',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
