# Generated by Django 4.1.6 on 2023-02-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0029_votestory_user_voted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveErrorChap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_story', models.CharField(max_length=100)),
                ('name_chapter', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
