# Generated by Django 4.1.6 on 2023-02-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0030_receiveerrorchap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='rating_score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=1),
        ),
    ]
