# Generated by Django 4.1.6 on 2023-03-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0032_remove_story_user_rate_alter_story_rating_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='number_of_chapter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='number_of_comment',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='number_of_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
