# Generated by Django 4.1.6 on 2023-03-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0033_alter_story_number_of_chapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='number_of_chapter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='number_of_comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='number_of_views',
            field=models.IntegerField(default=0),
        ),
    ]
