# Generated by Django 4.1.6 on 2023-03-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0034_alter_story_number_of_chapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
