# Generated by Django 4.1.6 on 2023-03-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0035_alter_chapter_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='posting_edit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='posting_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
