# Generated by Django 4.1.6 on 2023-03-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0037_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link_face',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
