# Generated by Django 4.1.6 on 2023-03-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0038_news_link_face_alter_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link_face',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
