# Generated by Django 4.1.6 on 2023-02-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_order_ordercombo_orderone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='OrderCombo',
        ),
    ]
