# Generated by Django 4.1.6 on 2023-02-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_payment_transaction_id_delete_ordercombo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_form',
            field=models.CharField(default='Chuyển Khoản Trực Tiếp', max_length=100),
        ),
    ]
