# Generated by Django 4.1.6 on 2023-03-14 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0036_chapter_posting_edit_alter_chapter_posting_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0004_alter_payment_transaction_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_chapter', models.IntegerField()),
                ('total_money', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
